### ISSUE TITLE
Add ability to use compact version of sequence of mappings

### ISSUE THREAD

**Issue by rypervenche** [Leont/yamlish#32]
Would it be possible to add an adverb or some way of getting the compact version of a sequence of mappings? I find that this formatting is much more common.

```yaml
---
sequence:
-
  a: b
  c: d
---
# compact
sequence:
- a: b
  c: d
```

Thanks!
