### ISSUE TITLE
YAMLish parse bug when no value present

### ISSUE THREAD

**Issue by paulprocacci** [Leont/yamlish#35]
```
some:
user:
    - username
```

Given the above example, YAMLish parses the above as:

`some => {user => [username]}`

Python's YAML module parses it as:

`'some': None, 'user': ['username']`

Given the indenting here, I suspect the YAMLish parser has gotten this wrong.

**Comment by FCO** [comment]
And:
```
bla:
ble:
```

Is not parsed:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/99834/170762856-8772f058-406b-45ae-8bb5-03ba8796c820.png">

**Comment by ldav1s** [comment]
This seems to be another variation of this issue:

```
---
- BLA:
    comment: &cp_comment approve for beta
- BLE:
- BLU:
    id: no id
    comment: *cp_comment
```

Also returns `Couldn't parse YAML`.
